### ISSUE TITLE
Line wrapping

### ISSUE THREAD

**Issue by fmalina** [matthewwithanm/python-markdownify#66]
Any chance of adding line wrapping to generated markdown with a line length option, say put a newline by default at 79 chars

**Comment by AlexVonB** [comment]
Hey!

Wrapping markdown is a bit more complicated than it should be:

1. Where do you allow breaks?
2. What happens if you cannot break?
3. Do you only handle text paragraphs?
    1. How do you handle tables?
    5. Do you break headlines, code, ...?
    6. Do you indent broken list lines?
    7. What about links in all of these elements??
8. Does your markdown renderer care for new line breaks?
9. What if a `#` gets sent to the beginning of a line, do you `\` it?
10. ...

It is probably best to use something like [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) that handles the [complex logic](https://github.com/stkb/Rewrap/blob/stable/core/Wrapping.fs) of wrapping text, especially [Markdown](https://stkb.github.io/Rewrap/specs/content-types/markdown/_markdown/), after converting to Markdown.

If you need wrapped Markdown output in you python code you could use [Pandoc](https://pypi.org/project/pypandoc/) with the [`--wrap`](https://pandoc.org/MANUAL.html#general-writer-options) option, although it adds substantially more code to you project than this small lib here.

Best
Alex

**Comment by fmalina** [comment]
Paragraphs only being naive to special cases would do all that's required in my usecase

**Comment by fmalina** [comment]
I think that's what I did years ago making text alternatives for HTML emails https://github.com/fmalina/django-emails/blob/main/emails/text_alt.py

**Comment by AlexVonB** [comment]
v0.11.2 now has the `wrap` and `wrap_width` options. Hope this helps!

**Comment by fmalina** [comment]
I tested this today and it worked a treat and will decrease my diffs massively when editing markdown files I got. I now wish it worked for ordered and unordered lists too, I only have single level deep ones

**Comment by AlexVonB** [comment]
Feel free to create a PR, I will have time too give it a try myself sometime next week.
